#!/bin/bash

CXX=clang++-14 CC=clang-14 colcon build --event-handlers=console_direct+ --cmake-args -GNinja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DBUILD_WITH_CUDA_MULTIARCH=ON -DBUILD_WITH_CUDA=ON -DBUILD_GTSAM_POINTS_GPU=ON -DGTSAM_POINTS_USE_CUDA=ON -DBUILD_WITH_CUDA=ON -DBUILD_TESTS=ON -DBUILD_TESTS_PCL=ON -DBUILD_DEMO=ON -DBUILD_EXAMPLE=ON -DROS_EDITION=ROS2 -DHUMBLE_ROS=humble
